### PR TITLE
slack: Add block color context

### PR DESCRIPTION
**Pull request by jfragoulis**
The PR provides a small fix to the slack message sent by cloud build.

The two commits have a detailed commit message so I will avoid duplication here.

### CODE REVIEW

**Comment by wyardley** [comment]
@emoryruscus @Aric1088 (just bugging you because of the recent merge / review)-  would you be able to get someone to look at this and / or #137?

Thanks to whoever rebuilt the Docker image (finally) as well.

**Review by Aric1088 — APPROVED** [review]

**Comment by ericnelson** [comment]
Any plans to merge this in and rebuild the docker image ?

**Comment by albosse** [comment]
Could some please review & build this?

**Pull request merged**
